spring:
  application:
    name: springboot-mybatis-annotation
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/liupengcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: admin
    dbcp2:
      initial-size: 5 #初始化连接数量
      min-idle: 5 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量
      max-idle: 10 #最小空闲连接:连接池中容许保持空闲状态的最小连接数量
      max-wait-millis: 10000 #最大等待时间

server:
  port: 80